apiVersion: v1
kind: Namespace
metadata:
  name: reeve
  labels:
    # Reject pods that run as root, escalate privileges or skip the default seccomp profile.
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/enforce-version: latest
