<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.12" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.12" />
    <PackageReference Include="Microsoft.Extensions.Diagnostics.HealthChecks.EntityFrameworkCore" Version="10.0.12" />
    <PackageReference Include="OpenTelemetry.Instrumentation.AspNetCore" Version="1.19.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Reeve.Application\Reeve.Application.csproj" />
    <ProjectReference Include="..\Reeve.Infrastructure\Reeve.Infrastructure.csproj" />
    <ProjectReference Include="..\Reeve.Contracts\Reeve.Contracts.csproj" />
  </ItemGroup>

</Project>
